name: Show the problem on every commit

on:
  push:

jobs:
  repro:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    name: on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-binstall

      - run: cargo binstall -y --verbose --pkg-url "{ repo }/releases/download/v{ version }/{ name }-{ target }-v{ version }{ archive-suffix }" --pkg-fmt "tgz" cargo-msrv
